### ISSUE TITLE
[BUG] - Erro ao adicionar cors no lazarus

### ISSUE THREAD

**Issue by LukeChagastec** [HashLoad/horse-cors#7]
Boa tarde.

Segue abaixo erro ao adicionar o Cors no Horse utilizando o lazarus.
Este processo tenta replicar o exemplo deste github.

Como reproduzir o erro:
1. Abrir um novo projeto;
2. Instalar as dependências (horse e cors);
3. Implementar chamada.

Na implementação, ao passar o "CORS" no tHorse.Use, um erro de tipagem é mostrado ao compilar.

Implementação no fonte.
![image](https://user-images.githubusercontent.com/89275370/231570433-060d2584-6551-45b6-83cf-4cf83372b2a1.png)

O que a classe THorseCore espera
![image](https://user-images.githubusercontent.com/89275370/231570576-427ee266-fbec-4526-90a4-5cada4361770.png)

O que é implementado no CORS
![image](https://user-images.githubusercontent.com/89275370/231570741-3031e1d4-a860-4bd7-a548-0a0aa398d6f9.png)

Este erro impede a utilização conforme o exemplo.

**Comment by andre-djsystem** [comment]
Qual versão do Lazarus vc está utilizando e qual a mensagem de erro?

**Comment by LukeChagastec** [comment]
Boa tarde.

* Versão 2.2.6
* FPC 3.2.2 
* OS: Win11 64 bits
* horse 3.1.0
* cors 1.0.6

![image](https://user-images.githubusercontent.com/89275370/231574755-4784dfef-3d1b-4575-97a9-ca2cbf33b49f.png)

Mensagens do compilador:
Compilar projeto, Alvo: OsServer.exe: Código saída 1, Erros: 2
controller.restserverunit.pas(55,10) Error: Wrong number of parameters specified for call to "CORS"
Horse.CORS.pas(45,11) Error: Found declaration: CORS(THorseRequest;THorseResponse;TNextProc);

**Comment by andre-djsystem** [comment]
Remova a diretiva {$mode objfpc}{$H+}  e adicione a diretiva mode delphi na sua unit.

{$MODE DELPHI}{$H+}

**Comment by LukeChagastec** [comment]
Agora Compilou.

Obrigado!

**Comment by andre-djsystem** [comment]
Fechado, não é um erro.
