### ISSUE TITLE
Erro de cors em uma rede especifica "The request client is not a secure context and the resource is in more-private addres space 'private'"

### ISSUE THREAD

**Issue by Jean-Paulo-Public** [HashLoad/horse-cors#8]
[ * Versão lazarus * ]

![image](https://github.com/HashLoad/horse-cors/assets/93294014/8cf6f823-8ddf-4645-aa76-5d6b871b9192)

Alguém tem ideia do que pode ser?

"""
Quando o computador está conectado na rede da empresa, a página apresenta o erro da imagem. 
A página consome a API, que testada via insomnia funciona normalmente, mesmo quando conectada na rede da empresa.
Quando o computador está conectado em qualquer outra rede a página carrega normalmente. 
Mesmo se a VPN estiver conectada.
"""

Será que é alguma configuração que tá faltando? alguém sabe ou tem alguma sugestão?

**Comment by viniciussanchez** [comment]
Acredito que você tenha que usar HTTPS nesse caso. Quanto ao insomnia, ele não valida CORS. O CORS é validado apenas quando a chamada a API é feito por aplicações JS.
